apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: privileged-container
    image: nginx:latest
    securityContext:
      privileged: true
  - name: test-container1
    image: ubuntu:latest
    securityContext:
      privileged: false
  - name: privileged-container2
    image: alpine:latest
    securityContext:
      privileged: true
  - name: test-container3
    image: redis:latest
    securityContext:
      privileged: false

